version: 2.1

aliases:
  - &cache_save
    save_cache:
      paths:
        - ~/.cache/yarn
        - node_modules
      key: v1-dependencies-{{ checksum "yarn.lock" }}
  - &cache_restore
    restore_cache:
      keys:
        - v1-dependencies-{{ checksum "yarn.lock" }}
  - &install_dependencies
    run: yarn install --frozen-lockfile --cache-folder ~/.cache/yarn

jobs:
  run-test:
    docker:
      - image: mcr.microsoft.com/playwright:v1.40.0-jammy
    parallelism: 4
    environment:
      NODE_ENV: development
    steps:
      - checkout
      - *cache_restore
      - *install_dependencies
      - *cache_save
      - run: SHARD="$((${CIRCLE_NODE_INDEX}+1))"; yarn test -- --shard=${SHARD}/${CIRCLE_NODE_TOTAL}

workflows:
  run-e2e-test:
    jobs:
      - run-test
