aliases:
  - &cache_save
    save_cache:
      paths:
        - ~/.cache/yarn
        - node_modules
      key: v1-dependencies-{{ checksum "yarn.lock" }}
  - &cache_restore
    restore_cache:
      keys:
        - v1-dependencies-{{ checksum "yarn.lock" }}
  - &install_dependencies
    run: 
      name: Install Dependencies
      command: yarn install --frozen-lockfile --cache-folder ~/.cache/yarn

commands:
  custom-command:
    parameters:
      run-command:
        type: string
        default: yarn test
#        default: yarn test:health-check
    steps:
      - run:
          name: Run Test
          command: << parameters.run-command >>

jobs:
  run-test:
    parameters:
      command-name:
        type: string
        default: yarn test
      parallelism:
        type: integer
        default: 4
    docker:
      - image: mcr.microsoft.com/playwright:v1.40.0-jammy
    parallelism: << parameters.parallelism >>
    environment:
      NODE_ENV: development
    steps:
      - checkout
      - *cache_restore
      - *install_dependencies
      - *cache_save
      - custom-command:
          run-command: << parameters.command-name >>
      - store_test_results:
          path: results.xml
      - store_artifacts:
          path: ./reports

version: 2.1
workflows:
  run-e2e-test:
    jobs:
      - run-test:
          command-name: SHARD="$((${CIRCLE_NODE_INDEX}+1))"; yarn test -- --shard=${SHARD}/${CIRCLE_NODE_TOTAL}
          filters:
            branches:
              only:
                - develop
                
  run-health-check:
    jobs:
      - run-test:
          command-name: yarn test:health-check
          parallelism: 1
          filters:
            branches:
              only:
                - health-check